### ISSUE TITLE
Problems after update the package

### ISSUE THREAD

**Issue by estebanbeck** [gilestrolab/rethomics#24] opened 2015-08-17 18:29 UTC
I update the R package and a script that was working (with DAM data) now is not working.

**Comment by qgeissmann** [comment] 2015-08-17 18:31
Yo, it would help if you:

* attached the script.
* Told me which line of script fails
* printed the error message

Cheers,
Q

**Comment by estebanbeck** [comment] 2015-08-17 18:40
This is the script, I copy paste!!!  I dont get where to attach it! sorry!! 

# change me!!!! This is the placement of the real data
DAILY_DATA_DIR <- "C:/Users/ebeckwit/Desktop/dailyData"

#I can define the query by extention
query = data.table(start_date=c("2015-07-07","2015-07-07","2015-07-07","2015-07-07","2015-07-07","2015-07-21","2015-07-21","2015-07-21","2015-07-21","2015-07-21"),
                        stop_date= c("2015-07-11","2015-07-11","2015-07-11","2015-07-11","2015-07-11","2015-07-25","2015-07-25","2015-07-25","2015-07-25","2015-07-25"), 
                        exp=c("A","A","A","A","A","B","B","B","B","B"),
                        machine_id=c("M001",
                                  "M002",
                                  "M003",
                                  "M004",
                                  "M005",
                                        "M001",
                                        "M002",
                                        "M003",
                                        "M004",
                                        "M005"), 
                   treatment=c("4-w-male_F-tube",
                               "5-CS-female_M-tube",
                               "2-w-male_M-tube",
                               "3-CS-female_F-tube",
                               "1-mock",
                               "4-w-male_F-tube",
                               "5-CS-female_M-tube",
                               "2-w-male_M-tube",
                               "3-CS-female_F-tube",
                               "1-mock"))
print(query)
#this is the magic moment
dt <- fetchDAMData(DAILY_DATA_DIR, query,reference_hour = 10.0, FUN=sleepDAMAnnotation)

The fetchDAMData is failing.
And the meassege is:

 Error in FUN(X[[i]], ...) : 
  Some of the dates are repeated between successive measument.
         This can happen if the recording computer change time (e.g. between winter and summer time)
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by qgeissmann** [comment] 2015-08-17 18:42
it is possibly a duplicate of #21

**Closed** 2015-08-18 10:34 UTC
Labels: duplicate
