### ISSUE TITLE
Ethoscope front page

### ISSUE THREAD

**Issue by estebanbeck** [gilestrolab/rethomics#35] opened 2015-11-26 16:11 UTC
Maybe it would be a good idea to have a comment field when starting an ethoscope, and the first 10 letter or so, could be another column in the front page. For instant to add the name of the person using a certain device. Also be able to sort the front page by the different columns would be nice.

**Comment by qgeissmann** [comment] 2015-11-27 17:06
Yo, I am moving this on the ethoscope repo.

**Closed by qgeissmann** 2015-11-27 17:06 UTC
Labels: enhancement

**Comment by qgeissmann** [comment] 2015-11-27 17:08
in fact it is a duplicate of https://github.com/gilestrolab/ethoscope/issues/25
